---
core:
  # server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
  server_url: https://web-server.com
  space_slug: <SPACE_SLUG>
  space_name: <SPACE_NAME>
  service_user_username: <USER_NAME>
  service_user_password: <PASSWORD>
options:
  delete: false
task:
  # server_url: https://<SPACE>.kinops.io/app/components/task   OR https://<SERVER_NAME>.com/kinetic-task
  server_url: https://web-server.com
  service_user_username: <USER_NAME>
  service_user_password: <PASSWORD>
http_options:
  log_level: info
  log_output: stderr
